# POST http://127.0.0.1:8000/fruits
# Accept: application/json
# Content-Type: application/json 


# {
#   "name": "a fruit"
# }

GET  http://127.0.0.1:8000/fruits
Accept: application/json
Content-Type: application/json 

# PUT http://127.0.0.1:8000/fruits/0
# Accept: application/json
# Content-Type: application/json 


# {
#   "name": "a fruit updated"
# }



